# Generated by Django 4.2.5 on 2023-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='home.size'),
        ),
    ]
