# Generated by Django 4.2.5 on 2023-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ManyToManyField(to='home.section'),
        ),
    ]
