# Generated by Django 4.2.5 on 2023-09-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
