# Generated by Django 4.2.5 on 2023-09-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
