# Generated by Django 4.2.5 on 2023-10-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
    ]
