# Generated by Django 4.2.5 on 2023-11-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
