# Generated by Django 4.2.5 on 2023-11-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_orderpayment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='razorpay_order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
